### ISSUE TITLE
Got an error and the server crashed after it

### ISSUE THREAD

**Issue by mal0andre** [Roundaround/mc-fabric-armor-stands#11]
```
---- Minecraft Crash Report ----
// I just don't know what went wrong :(

Time: 2023-09-15 17:33:25
Description: Ticking entity

java.util.ConcurrentModificationException
	at java.base@17.0.8.1/java.util.HashMap$HashIterator.nextNode(HashMap.java:1597)
	at java.base@17.0.8.1/java.util.HashMap$KeyIterator.next(HashMap.java:1620)
	at net.minecraft.advancements.critereon.SimpleCriterionTrigger.trigger(SimpleCriterionTrigger.java:60)
	at net.minecraft.advancements.critereon.InventoryChangeTrigger.trigger(InventoryChangeTrigger.java:55)
	at net.minecraft.advancements.critereon.InventoryChangeTrigger.trigger(InventoryChangeTrigger.java:51)
	at net.minecraft.server.level.ServerPlayer$2.slotChanged(ServerPlayer.java:252)
	at net.minecraft.world.inventory.AbstractContainerMenu.triggerSlotListeners(AbstractContainerMenu.java:219)
	at net.minecraft.world.inventory.AbstractContainerMenu.broadcastChanges(AbstractContainerMenu.java:176)
	at me.roundaround.armorstands.screen.ArmorStandScreenHandler.broadcastChanges(ArmorStandScreenHandler.java:212)
	at net.minecraft.server.level.ServerPlayer.tick(ServerPlayer.java:472)
	at net.minecraft.server.level.ServerLevel.tickNonPassenger(ServerLevel.java:739)
	at net.minecraft.world.level.Level.guardEntityTick(Level.java:480)
	at net.minecraft.server.level.ServerLevel.lambda$tick$6(ServerLevel.java:385)
	at net.minecraft.world.level.entity.EntityTickList.forEach(EntityTickList.java:54)
	at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:353)
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:897)
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:283)
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:824)
	at net.minecraft.server.MinecraftServer.handler$zdb000$carpet$modifiedRunLoop(MinecraftServer.java:7942)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:650)
	at net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:265)
	at java.base@17.0.8.1/java.lang.Thread.run(Thread.java:833)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at java.base/java.util.HashMap$HashIterator.nextNode(HashMap.java:1597)
	at java.base/java.util.HashMap$KeyIterator.next(HashMap.java:1620)
	at net.minecraft.class_4558.method_22510(class_4558.java:60)
	at net.minecraft.class_2066.method_24362(class_2066.java:55)
	at net.minecraft.class_2066.method_8950(class_2066.java:51)
	at net.minecraft.class_3222$2.method_7635(class_3222.java:252)
	at net.minecraft.class_1703.method_34246(class_1703.java:219)
	at net.minecraft.class_1703.method_7623(class_1703.java:176)
	at me.roundaround.armorstands.screen.ArmorStandScreenHandler.method_7623(ArmorStandScreenHandler.java:212)
	at net.minecraft.class_3222.method_5773(class_3222.java:472)
	at net.minecraft.class_3218.method_18762(class_3218.java:739)
	at net.minecraft.class_1937.method_18472(class_1937.java:480)
	at net.minecraft.class_3218.method_31420(class_3218.java:385)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:353)

-- Entity being ticked --
Details:
	Entity Type: minecraft:player (net.minecraft.class_3222)
	Entity ID: 1135
	Entity Name: Narkotiqu
	Entity's Exact location: 340.87, 63.00, -380.12
	Entity's Block location: World: (340,63,-381), Section: (at 4,15,3 in 21,3,-24; chunk contains blocks 336,-64,-384 to 351,319,-369), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,-64,-512 to 511,319,-1)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at net.minecraft.class_1937.method_18472(class_1937.java:480)
	at net.minecraft.class_3218.method_31420(class_3218.java:385)
	at net.minecraft.class_5574.method_31791(class_5574.java:54)
	at net.minecraft.class_3218.method_18765(class_3218.java:353)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:897)
	at net.minecraft.class_3176.method_3813(class_3176.java:283)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824)
	at net.minecraft.server.MinecraftServer.handler$zdb000$carpet$modifiedRunLoop(MinecraftServer.java:7942)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:650)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

i hope you can help me

**Comment by Roundaround** [comment]
While this happened with the armor stand screen, it seems like the error actually originated in some vanilla code. The fact that it's a ConcurrentModificationException on an internal class tells me there may be some other mod causing this.

There shouldn't be any opportunity for this particular exception to get thrown in Minecraft. My best guess is there's a performance mod trying to do some kind of multithreading that caused this.
